# Generated by CodiumAI
from deepgaze.deepgaze.motion_detection import DiffMotionDetector
import cv2


import pytest

class TestDiffMotionDetector:

    # Tests that the background image is set successfully
    def test_set_background_successfully(self):
        detector = DiffMotionDetector()
        background_image = cv2.imread('background.jpg')
        detector.setBackground(background_image)
        assert detector.getBackground() is not None
